In [1]:
import torch

In [59]:
# Создайте случайный FloatTensor размера 3x4x5
import random
a = torch.FloatTensor(torch.rand(3*4*5)).view(3,4,5)
a

tensor([[[0.6439, 0.8697, 0.0749, 0.0629, 0.8089],
         [0.3411, 0.0782, 0.4151, 0.9741, 0.4304],
         [0.6007, 0.2270, 0.6835, 0.2478, 0.0814],
         [0.7249, 0.3579, 0.8202, 0.5771, 0.5668]],

        [[0.3391, 0.6491, 0.5788, 0.1900, 0.8918],
         [0.7706, 0.2784, 0.7078, 0.7482, 0.8212],
         [0.5017, 0.6595, 0.1840, 0.5703, 0.3835],
         [0.5564, 0.1760, 0.0106, 0.5426, 0.3125]],

        [[0.0161, 0.2736, 0.2631, 0.7769, 0.9341],
         [0.1617, 0.2810, 0.0071, 0.5245, 0.5961],
         [0.0733, 0.9158, 0.2525, 0.0319, 0.9026],
         [0.3036, 0.2836, 0.6060, 0.3572, 0.0937]]])

In [60]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [64]:
# Приведите его к форме 6 X 10
c=a.reshape(6,10)
c

tensor([[0.6439, 0.8697, 0.0749, 0.0629, 0.8089, 0.3411, 0.0782, 0.4151, 0.9741,
         0.4304],
        [0.6007, 0.2270, 0.6835, 0.2478, 0.0814, 0.7249, 0.3579, 0.8202, 0.5771,
         0.5668],
        [0.3391, 0.6491, 0.5788, 0.1900, 0.8918, 0.7706, 0.2784, 0.7078, 0.7482,
         0.8212],
        [0.5017, 0.6595, 0.1840, 0.5703, 0.3835, 0.5564, 0.1760, 0.0106, 0.5426,
         0.3125],
        [0.0161, 0.2736, 0.2631, 0.7769, 0.9341, 0.1617, 0.2810, 0.0071, 0.5245,
         0.5961],
        [0.0733, 0.9158, 0.2525, 0.0319, 0.9026, 0.3036, 0.2836, 0.6060, 0.3572,
         0.0937]])

In [62]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b = torch.FloatTensor([1, 4, 2, 2, 1])
a*b

tensor([[[0.6439, 3.4787, 0.1497, 0.1259, 0.8089],
         [0.3411, 0.3127, 0.8302, 1.9482, 0.4304],
         [0.6007, 0.9081, 1.3670, 0.4956, 0.0814],
         [0.7249, 1.4316, 1.6403, 1.1541, 0.5668]],

        [[0.3391, 2.5962, 1.1576, 0.3800, 0.8918],
         [0.7706, 1.1137, 1.4155, 1.4964, 0.8212],
         [0.5017, 2.6380, 0.3680, 1.1407, 0.3835],
         [0.5564, 0.7039, 0.0212, 1.0853, 0.3125]],

        [[0.0161, 1.0943, 0.5262, 1.5538, 0.9341],
         [0.1617, 1.1240, 0.0142, 1.0490, 0.5961],
         [0.0733, 3.6631, 0.5051, 0.0638, 0.9026],
         [0.3036, 1.1343, 1.2120, 0.7144, 0.0937]]])

In [74]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.mm(c,c.T)
# torch.matmul(c,c.T)

tensor([[3.2638, 2.1387, 3.2202, 2.1275, 1.9200, 2.3602],
        [2.1387, 2.9283, 3.0024, 1.7147, 1.3843, 1.5839],
        [3.2202, 3.0024, 4.1092, 2.3028, 2.4057, 2.6625],
        [2.1275, 1.7147, 2.3028, 1.9256, 1.6485, 1.4999],
        [1.9200, 1.3843, 2.4057, 1.6485, 2.3559, 1.5623],
        [2.3602, 1.5839, 2.6625, 1.4999, 1.5623, 2.3997]])

In [88]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable
x = Variable(torch.FloatTensor([1]),   requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward([x, z, t])

(x.grad, z.grad, t.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [94]:
# Создайте единичный тензор размера 5x6
t=torch.ones(5,6)
t

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [104]:
# Переведите его в формат numpy
import numpy as np
t.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [241]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [508]:
from torch import nn 
from torch import optim

In [509]:
x = torch.FloatTensor([1])
w1 = Variable(torch.FloatTensor([1]), requires_grad=True)

y = x**w1 - 2*x**2 + 5

In [510]:
criterion = nn.MSELoss()

In [511]:
optimizer = optim.SGD([w1], lr=0.01)

In [512]:
layer=nn.Linear(1,1,bias=False)

In [513]:
layer.weight, layer.bias

(Parameter containing:
 tensor([[0.0828]], requires_grad=True),
 None)

In [514]:
optimizer.zero_grad()
x = torch.FloatTensor([2])

pred = x ** layer(torch.FloatTensor([1])) -2 * x**2 + 5
loss = criterion(pred, y)

In [515]:
loss

tensor(35.2949, grad_fn=<MseLossBackward0>)

In [516]:
loss.backward()
optimizer.step()

In [517]:
pred

tensor([-1.9410], grad_fn=<AddBackward0>)

In [518]:
print(layer.weight.grad)

tensor([[-8.7222]])
